### GET /user
GET http://localhost:3000/user


> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.data.toLowerCase() === 'user service', "Response is not correct");
});
%}

### GET /dashboard
GET http://localhost:3000/dashboard

> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.data.toLowerCase() === 'dashboard service', "Response is not correct");
});
%}

### GET /auth
GET http://localhost:3000/auth

> {%
client.test("Request executed successfully", function() {
    client.assert(response.body.data.toLowerCase() === 'auth service', "Response is not correct");
});
%}

### POST /auth
POST http://localhost:3000/auth

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

### POST /user
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "a@a.com",
  "password": "content"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}
